name = "rya-worker"
main = "build/worker/shim.mjs"
compatibility_date = "2024-07-26"

kv_namespaces = [
    { binding = "rya-worker", id = "308075fe7e744602aaec65967711e6c9"}
]

[[d1_databases]]
binding = "ray-worker"
database_name = "ray-worker"
database_id = "218a723e-be1a-4a66-bdc3-7290f5ba0b60"

[build]
command = "cargo install -q worker-build && worker-build --release"
